### ISSUE TITLE
Remove vue cli favicon

### ISSUE THREAD

**Issue by matthewma7** [girder/girder_web_components#113]
I don't have a strong opinion about this. 
The Vue favicon doesn't look so bad, but I think the default vue favicon should be removed considering this repo is a library for girder.

**Comment by zachmullen** [comment]
We have a girder favicon we can use for the app demo, or we can just remove it altogether.

**Comment by waxlamp** [comment]
I vote for using the Girder favicon. It should certainly not be the Vue favicon.
