### ISSUE TITLE
Add ability to browse across user folders and collections to DataBrowser

### ISSUE THREAD

**Issue by matthewma7** [girder/girder_web_components#119]
Currently, the DataBrowser requires an initial location and is not able to browse across user folders and collections. A new prop can be added to allow the DataBrowser to be able to browse everything the user has access to across user folders and collections.
This would also make location prop optional.

**Comment by subdavis** [comment]
@matthewma7 thanks for logging this issue.  I've been missing this feature as well, so I think it's time someone added it.

Could we briefly discuss how this implementation will work?  Are collections / users going to behave as "folders" to the Data Browser such that navigation within the browser works the same?  Will the list of users be browse-able? How will this affect the breadcrumb?  I think it would be good to have the icon (currently a globe) represent user/collection, but I don't know how to allow the user to "ascend" from user/collection list to the very root which would just be:

```
+---------------------------------------------------------+
| Breadcrumb: What goes here?                             |
+---------------------------------------------------------+
|                                                         |
| X Users                                         100MB   |
|                                                         |
| X Collections                                   3.4GB   |
|                                                         |
+---------------------------------------------------------+
```

Maybe @jtomeck should be present and sign off on whatever we decide.  Maybe the two of you could talk about it.

I think I would enjoy adding this feature, but I'm a bit busy at the moment so if you have some allocation to spend, that would be awesome.  Thanks!

**Comment by matthewma7** [comment]
Hi @subdavis, these are great questions and suggestions. 
> Are collections / users going to behave as "folders" to the Data Browser such that navigation within the browser works the same

I think yes. 
> Will the list of users be browse-able?

I didn't fully understand the question, but I think yes?

> Will the list of users be browse-able? How will this affect the breadcrumb? I think it would be good to have the icon (currently a globe) represent user/collection

I am thinking have the globe goto the page you have shown above, and [globe icon]/users and [globe icon]/collections to represent users and collections respectively. After that, the rest of breadcrumb remains what it is. so, [globe icon]/users/matthewma, [globe icon]/collections/collectionA

And this does make the breadcrumb long and we may not want to limit the user, so additional prop with default true or false will be provided.  

I definitely could have missed something here, other thoughts?

**Comment by subdavis** [comment]
I think we're on the same page.

To conserve breadcrumb space, I think it would be nice to do the following:

For users regular folders (notice that `users / username` has been condensed):

`🌎 / 😃 username / folder_name`

For collection regular folders:

`🌎 / 📚 collection_name / folder_name`

For users:

`🌎 / users`

For collections: 

`🌎 / collections`

For root:

`🌎 /`

cc @zachmullen: I think Matthew's feature request is good, but it will be a pretty invasive change to data-browser.  Could you sign off?

**Comment by brianhelba** [comment]
This would be a great feature.

Note, in light of the recent changes to the user listing endpoint, you'll need some special logic to exclude the users top level from anonymous end users.

Anonymous end users can still see the collections listing and can still access user home directories if they somehow know the user ID in advance (if they navigate away, I guess they can't get back?).

**Comment by jeffbaumes** [comment]
I like the suggested breadcrumb. I don't want to overdo this, but it may make sense to also have a (optional) home location button/icon to go to the currently logged in user (if logged in). It may be a common place a user would want to go, and may be hard to navigate to if there are lots of users. That could be a separate PR or could be rolled into this.
