### ISSUE TITLE
Breadcrumb broken.

### ISSUE THREAD

**Issue by subdavis** [girder/girder_web_components#130]
Navigating to a folder through search or entering a child folder makes the breadcrumb show only the parent, not the current working folder.  Ascending corrects the issue.

**Comment by matthewma7** [comment]
If this is the behavior of the latest master.
I believe https://github.com/girder/girder_web_components/pull/125 would resolve this.

**Comment by matthewma7** [comment]
Resolved by https://github.com/girder/girder_web_components/pull/133
