### ISSUE TITLE
Add in detail view to hierarchy widget?

### ISSUE THREAD

**Issue by mgrauer** [girder/girder_web_components#163]
Does it make sense to have a detail view in the hierarchy widget like in the attached screenshot? Can we make it so that the actions are extensible?

Should this be a feature in the general library or be project specific?

![Screenshot from 2019-10-02 14-59-17](https://user-images.githubusercontent.com/595023/66093393-16941200-e55e-11e9-8cfa-91777c60d044.png)

**Comment by matthewma7** [comment]
If you mean the detail view on the left we have a [pending PR](https://github.com/girder/girder_web_components/pull/93) for it.
IMHO, adding custom actions is something this library could support. 

PS: The detail view is not **in** the hierarchy widget ([Data Browser](https://github.com/girder/girder_web_components/blob/master/src/components/DataBrowser.vue)).
This library follows a composition over inheritance pattern.

**Comment by subdavis** [comment]
> This library follows a composition over inheritance pattern.

What that means for your app is that you have to decide how to map user interactions from the data browser into other widgets like the details view.  You could do this simply by forwarding the list of "selected" rows into the details widget (example above).  You could also use the details widget alone and let some other UI tell it what to show.
