### ISSUE TITLE
Alter search results view?

### ISSUE THREAD

**Issue by mgrauer** [girder/girder_web_components#165]
Should we allow the search results view to be altered? E.g., to show a breadcrumb or to calculate some new text value based on the search results (say a function of the Item's metadata or path), or even a thumbnail?

Should this be in the library or project specific?

**Comment by matthewma7** [comment]
Hi @mgrauer, when you say search result view. Do you mean the red area in the screenshot below?
![image](https://user-images.githubusercontent.com/3123478/66125345-b54b5d80-e5b4-11e9-9f84-6cdc2a649e1b.png)

**Comment by mgrauer** [comment]
Yes
