### ISSUE TITLE
Scaling on MacOS is comically large

### ISSUE THREAD

**Issue by subdavis** [girder/girder_web_components#182]
I just looked at a GWC app on @mgrauer's laptop and all the components were positively huge.  The login component took up like 40% of his viewport.   I'd like to point the finger at Vuetify, but we should probably spend more time testing cross-platform.  I've only been testing on Firefox and Chrome on Ubuntu 18.04.

In general I'm still not happy with the amount of space that Vuetify-based components take up.

@mgrauer what are the dimensions of your display?  Could you fullscreen the app and take a screenshot?  thanks.

**Comment by zachmullen** [comment]
What browser?

**Comment by mgrauer** [comment]
1280x800. Chrome. 
<img width="1280" alt="Screen Shot 2019-10-09 at 1 23 25 PM" src="https://user-images.githubusercontent.com/595023/66504822-0a491100-ea98-11e9-9fed-4390542c2571.png">

**Comment by subdavis** [comment]
I'm starting to wonder if this is my fault fo changing my DPI settings.  Here's how a 1200x800 screen looks on my display.   You'll notice the Authentication component takes up much less vertical space.

![Screenshot from 2019-10-09 13-29-10](https://user-images.githubusercontent.com/4214172/66505243-f4881b80-ea98-11e9-92fd-3a6bcd8e3c8b.png)

**Comment by jeffbaumes** [comment]
Here's the GWC demo on my macbook pro, which I think is not too different to Mike's (native resolution is 2560x1600, "feels like" a sharp 1440x900):

![image](https://user-images.githubusercontent.com/81305/66505289-0cf83600-ea99-11e9-9acd-87475b3b36ab.png)

@mgrauer I'm curious, are you on the default setting in your Display settings?

![image](https://user-images.githubusercontent.com/81305/66505347-2d27f500-ea99-11e9-8578-3320b8bd4bf8.png)

**Comment by mgrauer** [comment]
Yes default display settings. It is an early 2015 13 inch mac book pro with retina display.

I thought it was a 2016 until I looked it up. Suddenly it feels old and slow.

**Comment by jeffbaumes** [comment]
Indeed it seemed the extra 100 vertical pixels in 2016 was great news to some. Time for an upgrade?

https://www.reddit.com/r/apple/comments/5dopnu/why_does_the_2016_macbook_pro_have_a_different/

"GPU performance has improved enough to mitigate the performance hit from scaling, and frankly 1280x800 and 1440x900 on the 13" and 15" were too big."

**Comment by zachmullen** [comment]
To me this is just another justification for us to avoid mucking around with our own CSS whenever possible, and to instead prefer vuetify semantics and punt this problem upstream to them. It's going to be the case that things look (sometimes wildly) different across different platforms, but if we stick to semantic-driven UI, we don't have to worry about this incredibly frustrating and expensive problem.
