### ISSUE TITLE
Support for Vuetify dark theme

### ISSUE THREAD

**Issue by matthewma7** [girder/girder_web_components#195]
Vuetify has good built-in support for the dark theme. However, at this moment, GWC component doesn't support the dark theme well due to some hard-coded value or missing configuration.

**Comment by matthewma7** [comment]
Specifically, we are working on an application that uses a dark theme. Most components work well with Vuetify dark theme but GWC does not.

![2019-10-30_15-56-36](https://user-images.githubusercontent.com/3123478/67894483-048e9a80-fb2f-11e9-82f9-18849d4b1100.png)

![2019-10-30_15-58-59](https://user-images.githubusercontent.com/3123478/67894548-21c36900-fb2f-11e9-951d-4c7f8f081d40.png)

![2019-10-30_15-59-35](https://user-images.githubusercontent.com/3123478/67894551-238d2c80-fb2f-11e9-921a-1892e62e6d54.png)

**Comment by zachmullen** [comment]
Big +1 from me. Maybe we could make this a dynamic switch on our demo app so you can very easily see both modes. The goal should be simply setting `light` or `dark` on the very top `v-app` should be sufficient to make everything look correct. That might not be possible, but we should try and get as close to it as we can.

**Comment by matthewma7** [comment]
Since the application decided to use a dark theme. If it's ok, I'll give it a try with the project today.

**Comment by zachmullen** [comment]
One other thing -- if we manage to achieve this goal of supporting both modes via a top-level `v-app` switch, we should advertise that as a feature in the README.

**Comment by matthewma7** [comment]
Hm, the font in the upload is inheriting its color so the contrast is a little low.
![image](https://user-images.githubusercontent.com/3123478/67949605-5af6ea00-fbbe-11e9-8606-9da99ec676e2.png)
Maybe, in this case, we could use a darker shade of grey when the dark theme is applied.

**Comment by zachmullen** [comment]
If you want, I can make that change if you push your topic branch.
