### ISSUE TITLE
Permalink to resource

### ISSUE THREAD

**Issue by mgrauer** [girder/girder_web_components#196]
How hard would it be to add a permalink to a resource, such as a view of an individual folder or item? Is this a concern of an app that uses GWC rather than GWC itself?

**Comment by zachmullen** [comment]
The main component that comes to mind here is the DataBrowser; there may be others that would benefit from this, but let's just focus on that one.

While GWC's policy is not to assume anything about a router, and not to mess with URL state, I do believe we should support this case, namely via a prop passed to DataBrowser along the lines of `toPattern`, which if passed will change the rows to use the `to` prop and will expand wildcards in the template. Another option would be to use a slot for the rows, but that's a little more cumbersome for downstreams.

**Comment by subdavis** [comment]
@mgrauer this was originally a feature for dandi, but dandi is abandoning GWC data browser, so I'm going to close this issue.  We can revist if another project wants this.
