### ISSUE TITLE
access control dialog shows up on other users, collections.

### ISSUE THREAD

**Issue by subdavis** [girder/girder_web_components#202]
Even though the access control request fails with 403 forbidden, the dialog still pops up with whatever was last looked at.

Dialog should not appear if the request fails, I think?   

cc @matthewma7

**Comment by matthewma7** [comment]
😆Probably yes. I'll take a look now.

**Comment by matthewma7** [comment]
Hi, @subdavis I created a PR try to address this issue. Could you take a look and see if the approach looks good to you? 🙂 If it does I'll add a test and finish that PR.

**Comment by subdavis** [comment]
Solved in #203
