### ISSUE TITLE
Proper support of all page size in Data Browser

### ISSUE THREAD

**Issue by matthewma7** [girder/girder_web_components#205]
It turns out Girder doesn't actually support 'all' option. (Is that true?). When no limit param is passed in, Girder will set it to 50. It looks like we should remove the 'all' option from GWC or add the 'all' option support to Girder.
@subdavis @zachmullen

**Comment by subdavis** [comment]
Those params get pushed directly to the mongo query.  So yeah not providing the parameter would result in 50.   But you can send `0` as the limit and mongo will return the full list.

It's a leaky abstraction, but I suppose it works.

**Comment by matthewma7** [comment]
Oh, 0 is interesting. I'll change the title and create a quick PR for it.

**Comment by subdavis** [comment]
@matthewma7 I don't necessarily think that allowing a user to show "all" is a good idea. A max page size of 50 might be a better limit.  You could certainly lock up the page with too many elements for large folders.

Unless there's an explicit use case for seeing more than 50 items on a page, might be easier just to remove that from the list of options (as well as validate the parameter so parent components couldn't add it back)

**Comment by matthewma7** [comment]
I think removing the 'all' from default makes sense, but if a downstream app chooses to do that, we should allow it?

**Comment by subdavis** [comment]
I don't see how we could allow it without adding the `-1` to `0` transform in DataBrowser.vue, at which point we might as well support it fully?  I'd endorse either all or nothing.  Full support or no support.  

What do you think?

**Comment by matthewma7** [comment]
I meant that we implement the `-1 to 0` magic, but don't provide the 'all' option by default, by changing the new [items-per-page-options](https://github.com/girder/girder_web_components/pull/204/files#diff-20a85c2a028ea24e3d92a12b008ceda7R55)'s default value.

**Comment by subdavis** [comment]
That sounds fine.
