### ISSUE TITLE
Allow for copy link address in item details view, from download

### ISSUE THREAD

**Issue by mgrauer** [girder/girder_web_components#225]
You can see this behavior in gui.dandiarchive.org. If I go into an item details view, there is a download button, but I cannot get the link address target from the button (right clicking doesn't allow me the "copy link address" action). Could we enable the download link to be visible somehow (right click menu is fine)?

**Comment by yarikoptic** [comment]
and I might "steal" the solution for datasets.datalad.org ;) (haven't had yet a chance to look in what JS magic I need to do for that)

**Comment by mgrauer** [comment]
Just to clarify: the download action button in the item details view is a `div` behind the scenes, if it were an `a` anchor tag then the browser would display a `copy link address` action. I'm not sure if there is some magic solution other than changing to an anchor, I wasn't suggesting anything fancy, whatever works.
