### ISSUE TITLE
Consider Jest vs. Mocha-webpack

### ISSUE THREAD

**Issue by zachmullen** [girder/girder_web_components#26]
When creating this project, mocha-webpack was chosen over jest as the testing framework. Was there a rationale for that, or was it arbitrary?

I haven't done a deep comparison, but there are some attractive things about jest:

* It's more opinionated: rather than bring your own mocking library and assertion library, they're built in. We could get rid of dev dependencies on chai and sinon.
* Coverage is apparently built in. I haven't tried this, and it may be too good to be true, but that's the claim.
* Screenshot comparisons built in

@jbeezley thoughts? I haven't tried jest myself, just been reading about it.

**Comment by zachmullen** [comment]
To report back on the second point, it was indeed too good to be true. I spun up a test app with `vue ui` that used jest, and passing the coverage flag did not work.

![screen shot 2018-09-21 at 8 13 09 am](https://user-images.githubusercontent.com/555959/45880532-3226e300-bd76-11e8-9460-a4f7e26857d7.png)

Even when experimenting with all the other coverage related jest flags I could not get any results reported. I don't think vue-cli has any solution for this in either framework at this time.

**Comment by jeffbaumes** [comment]
Getting coverage working without a lot of mucking around sounds like a big win to me.

**Comment by jbeezley** [comment]
I only chose mocha because it was closest to what we were using before.  If jest supports coverage, then I think that's good enough reason to switch.

**Comment by jeffbaumes** [comment]
As an aside, I was able to get coverage on a fresh repo created with `@vue/cli` without changing the code by adding what I assume is a more inclusive range in the jest settings:

```
    "collectCoverageFrom": [
      "**/*.{js,vue}",
      "!**/node_modules/**"
    ],
```

This outputs the following (albeit with a bunch of noise):

![image](https://user-images.githubusercontent.com/81305/45881588-95fedb00-bd79-11e8-86b9-abbe345cef34.png)

**Comment by zachmullen** [comment]
It seems like everyone is generally OK with switching to jest in theory. The coverage thing is compelling enough, but I also really like being able to remove sinon and chai -- they're just two more random words that developers of this library will have to grok, separate documentation corpuses to ingest, etc.

I'll make the switch, it should be a big change at this point.
