### ISSUE TITLE
Show better error for email verification required

### ISSUE THREAD

**Issue by subdavis** [girder/girder_web_components#306]
> UI for Girder itself shows the user an error message saying email verification is required and provides a link to resend the verification request email.  The GirderAuthentication component just shows the error message indicating email verification is required, but does not provide a link to resend the verification request email.  I don't see any props on the component that look promising for customizing this behavior, so is the only option for the user to try logging in through Girder itself?

**Comment by jeffbaumes** [comment]
@subdavis, are you comfortable having this issue assigned to you?

**Comment by subdavis** [comment]
Thanks for the reminder.
