### ISSUE TITLE
Search Component

### ISSUE THREAD

**Issue by jtomeck** [girder/girder_web_components#40]
I have put together some screens for a search component. The consensus from people that I've talked to is that some/much of this can not be done. I wanted to post anyway to share the ideas and discuss the parts that can be done, as well as potential ways to improve upon how search is currently done in Girder.

![01 file list](https://user-images.githubusercontent.com/1560779/46870199-f1157200-cdfb-11e8-9ec4-6ebe15c50d18.jpg)
Fixed position search bar on the bottom of the screen

![02 auto complete](https://user-images.githubusercontent.com/1560779/46870201-f1ae0880-cdfb-11e8-85d9-b2055483a0b1.jpg)
Autocomplete

![03 advanced search](https://user-images.githubusercontent.com/1560779/46870202-f1ae0880-cdfb-11e8-9255-1b7916ce8b21.jpg)
Clicking the icon next to search (advanced search) opens a dialogue/bottom sheet style component. The fields are just placeholders that I stole from Google Drive. My thought is that there could be tabs to cover different search modes. More modes could be added, ie. for QIDW, we needed a search specifically for DICOM metadata.

![04 results](https://user-images.githubusercontent.com/1560779/46870203-f1ae0880-cdfb-11e8-8479-c569070a142d.jpg)
Results page similar to hierarchy widget but stripped down. Paths to files are shown and this list could be broken down based on what type of result is displayed (ie - items/folders/users/etc.)

Let's discuss

**Comment by danlamanna** [comment]
I don't know how people feel about the search bar at the bottom vs the top. The bottom reminds me more of text editors and less of the web.

**Comment by jtomeck** [comment]
@danlamanna - I'm open to having it at the top, it just didn't look like it fit as nicely to me. Much of that could have been the "mock UI" that I designed making it seem awkward to me, but the beauty of it being a component is that it could be used in either, right?

**Comment by danlamanna** [comment]
I don't have a strong opinion, I'm just curious what others thing. Otherwise, the design is perfectly adequate :stuck_out_tongue:.

**Comment by subdavis** [comment]
@jtomeck I'm thinking about how to factor the data table out of FileBrowser to make it useful for arbitrary paginated lists.

One of the features of Girder is that it's paginated by type -- you get different lists for "user", "item", "folder" etc.

How do you think that would look in this case?

**Comment by danlamanna** [comment]
I don't know if this is directly applicable here or not, but I like the way GitHub handles different search result types. Searching "python" for instance:
![github-py-search](https://user-images.githubusercontent.com/608229/48497150-9491e200-e801-11e8-989d-41f2ac955015.png)

**Comment by subdavis** [comment]
Started playing with this today.

![screenshot_20181220_161039](https://user-images.githubusercontent.com/4214172/50311034-d140a100-0471-11e9-89d9-edc2fc74cd68.png)

![screenshot_20181220_160756](https://user-images.githubusercontent.com/4214172/50310922-7dce5300-0471-11e9-86a0-9d6556e5ac0d.png)

I started out with it on the top, but that could be configurable.  Everything looks too big to me right now, which is one of my biggest complaints about Vuetify.  The default paddings are all pretty enormous.

I also don't think we're going to be able to show the full path for each search result in the quick view.  Those paths don't come back from `/resources/search` so each would have to be another query. 

Finally, I'm playing with the solo style input text box.  Let me know if I've strayed too far from the herd or if there are other things you'd like to see.

**Comment by subdavis** [comment]
Girder advanced search only has 2 things to configure:

* mode: prefix or full text
* type: user, item folder.

I wonder if this changes how we think about the advanced search config UI -- those two things don't really need a full-width expansion.  This feature may need input from other girder developers about how search may change in the near future.  If I were doing this now, I'd probably have a simple popover menu with radio buttons for prefix/text and a checkbox group for type.

[Maybe something like this](https://vuetifyjs.com/en/components/menus#example-popover) ?

CC @jtomeck @zachmullen @jeffbaumes
