### ISSUE TITLE
Use SCSS instead of Stylus

### ISSUE THREAD

**Issue by matthewma7** [girder/girder_web_components#41]
Hi, I know Girder has been using Stylus. However, Vuetify is [moving away from Stylus to SCSS in 2.0](https://www.patreon.com/posts/september-2018-21931872), which I guess is motivated by a [feature request](https://github.com/vuetifyjs/vuetify/issues/2371).
And as a core library, I think if we could ask people to learn as little as possible to be able to understand the code, create PR, or hack the code it is better. SCSS is a superset of CSS, so anyone knows CSS would start to write or modify style with the minimal learning curve.

**Comment by zachmullen** [comment]
> And as a core library, I think if we could ask people to learn as little as possible to be able to understand the code, create PR, or hack the code it is better. SCSS is a superset of CSS, so anyone knows CSS would start to write or modify style with the minimal learning curve.

Stylus is also a superset of CSS, so we'll need a different argument to motivate a switch. That thread you linked seems to indicate their interest in moving has to do with stylus not being as well supported, which might be compelling. Is there anything other than that that would make the switch attractive to our community that already has a lot of inertia with Stylus? I am not familiar with SCSS, maybe there are some cool features not present in stylus?

**Comment by matthewma7** [comment]
Feature-wise, it sounds like SASS/SCSS may be a little better, but I don't know without looking into it.
So, other than feature and support the [general fondness and prevalence of SCSS](https://2017.stateofjs.com/2017/css/results) could be a reason.
Except for inertia, does Girder community like Stylus for some particular reason? I was thinking girder 3 and this component library is a good chance for changing.

**Comment by zachmullen** [comment]
Popularity is definitely a reason to consider a switch. As long as there isn't a big cost to switching from stylus to scss, it might be worthwhile just for that reason.

**Comment by matthewma7** [comment]
I agree. And the cost is small at this moment because the code base here is small.

**Comment by zachmullen** [comment]
A PR that shows the code changes required to make the switch (even if just scoped to a single existing component) is probably the best way to push this forward. Feel free to make such a PR if you think it's an easy change.

**Comment by matthewma7** [comment]
It should easy, I will create such PR.

**Comment by jeffbaumes** [comment]
This does indeed look a bit grim:

https://github.com/stylus/stylus/graphs/contributors

This (ad-ridden) page seems to do a decent job summing up pros and cons of the two:

https://www.slant.co/versus/762/764/~stylus_vs_sass

* Stylus: clean syntax but not maintained.
* SCSS: advanced capabilities but depends on Ruby stack.

**Comment by matthewma7** [comment]
It looks like all popular CLI including vue-cli and create-react-app use [node-sass](https://www.npmjs.com/package/node-sass) which uses [libsass](https://github.com/sass/libsass), so no Ruby requirement as a user.

**Comment by zachmullen** [comment]
One thing that is currently missing for us is linting -- there is no available tooling to allow linting of stylus in Vue single file components. If we could get linting in place easily with SASS/SCSS, that would be a significant advantage.

**Comment by jcfr** [comment]
FWIW, SCSS is what was used in Midas3. See https://github.com/midasplatform/Midas/tree/master/core/public/scss

And here was the lint config ... https://github.com/midasplatform/Midas/blob/master/.scss-lint.yml

**Comment by matthewma7** [comment]
Closed by https://github.com/girder/girder_web_components/pull/42
