### ISSUE TITLE
Markdown edit/render component

### ISSUE THREAD

**Issue by mgrauer** [girder/girder_web_components#47]
Does this make sense to have as a general component? It is a generally useful feature to have for displaying info about e.g. a collection or folder, or could even been used for an item or folder if a README.md is found.

Should it be used only for metadata or for file data, or is that question outside the scope of what this component should do, as in, it should take in some data and then either edit or render, regardless of the source of the data?

**Comment by zachmullen** [comment]
* https://github.com/girder/girder-vue/blob/master/src/views/Markdown.vue
* https://github.com/girder/girder-vue/blob/master/src/views/MarkdownEditor.vue

**Comment by jcfr** [comment]
I think it makes sense to have it as a general component. 

Ideally, every description field should support markdown.

Also, it should be possible include and render images from the current collection (private or public) or any public collection in Girder.

> Should it be used only for metadata or for file data, 

I think any file with .md extension should be rendered. 

By default, I think `README.md` should be used as collection description.

**Comment by subdavis** [comment]
@zachmullen wouldn't this be part of the item/folder details component?

I've lost track of where we discussed it, but @jtomeck created the view below and I think we taked about making  that side-bar details view its own component.

![3b633624-3de0-4967-a43c-331195a17f90](https://user-images.githubusercontent.com/4214172/48213333-8d735b80-e34b-11e8-9641-c55b2775792a.png)

Do we need a new issue to track that work?

**Comment by zachmullen** [comment]
I think the README display should take up the full width of the component. What does that sidebar component look like on mobile?

**Comment by subdavis** [comment]
I see, there are actually a couple of disctinct feature here.

1. Show the README in a folder regardless of selection.
2. Show the markdown-supported description of whatever the selected item is.

Should that full-width README be a feature toggle for the FileBrowser?  Something to indicate that if there is one, it should be shown full-width below the item table?

**Comment by jcfr** [comment]
> created the view below and I think we taked about making that side-bar details view its own component.

Nitpick: To minimize mouse travel, what about adding actions above the selection summary ?

Or may be action should be on the left. With two modes for the left toolbar (small or wide) .. like what you have 

* on on GitLab

![image](https://user-images.githubusercontent.com/219043/48214528-23a88100-e34e-11e8-9ab5-14ce0b8619b6.png)


![image](https://user-images.githubusercontent.com/219043/48214551-2e631600-e34e-11e8-9460-48674548ed44.png)

* on Gmail on the right.

![image](https://user-images.githubusercontent.com/219043/48214454-fb208700-e34d-11e8-8836-1404c42e9af9.png)

![image](https://user-images.githubusercontent.com/219043/48214483-083d7600-e34e-11e8-8628-8e038d95cf1d.png)

**Comment by mgrauer** [comment]
>By default, I think README.md should be used as collection description.

We allow collections to have markdown description (saved in the DB), so we'd have to deal with db vs README.

But for the sake of clear scope, all I wanted in this issue was a edit/render component, then all of the discussion for how to use it can be decided in the appropriate place.

**Comment by jcfr** [comment]
> Should that full-width README be a feature toggle for the FileBrowser?

I think Yes. 

I envision having collection where the default "item" to render would be an image, a video, a 3d image rendered with vtk.js, ...  that is why disabling the support for README.md is important, may be this could be based on metadata found in the collection ?

**Comment by jcfr** [comment]
> have markdown description (saved in the DB

Or never save the description in the database, have an item created for you by default  if none exist ?

We should also decide if an item saved as URL and named README.md is rendered. I think it should.

**Comment by jeffbaumes** [comment]
> Or never save the description in the database, have an item created for you by default if none exist ?

Interesting, so the markdown editor would just become part of a general text editor built into Girder?

**Comment by jcfr** [comment]
> the markdown editor would just become part of a general text editor built into Girder?

Indeed.
