### ISSUE TITLE
Build error due to spread operator

### ISSUE THREAD

**Issue by finetjul** [girder/girder_web_components#60]
Here is an error I got when run webpack after importing the upload.js file:
```
ERROR in ./node_modules/@girder/components/src/utils/upload.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
SyntaxError: C:/Work/.../node_modules/@girder/components/src/utils/upload.js: Unexpected token
(62:6)

  60 |       size: this.file.size,
  61 |       mimeType: this.file.type,
> 62 |       ...this.params,
     |       ^
  63 |     }))).data;
  64 |
  65 |     if (this.upload.behavior && uploadBehaviors[this.upload.behavior]) {
```

I can fix the error by applying a babel-loader rule with the plugin-proposal-object-rest-spread on node_modules but aren't we supposed to not apply babel-loader rules to node_modules ?

**Comment by zachmullen** [comment]
Since you're importing the source files rather than the prebuilt UMD module (which is ES5), you'd need to use the babel loader on that. You could just use a loader rule for the `node_modules/@girder/components/src` include pattern in this case.

**Comment by finetjul** [comment]
Yep, both solutions (use of UMD and babel_loader only on girder components files) work. 
Thanks !
