### ISSUE TITLE
Handle 'Admin approval required' registration

### ISSUE THREAD

**Issue by matthewma7** [girder/girder_web_components#67]
The registration and related component are not handling 'Admin approval required' registration mode. 

This is caused by the fact 'Admin approval required' user creating endpoint returns 200 OK instead of an error status such as 400, which is what will be returned if registration is closed. This could be handled by checking the existence of authToken in the user creating response.

**Comment by matthewma7** [comment]
If it sounds good, I would work on this for the project that required this.

**Comment by zachmullen** [comment]
Sure, that's fine, though it would be nice if we could detect this condition in a more explicit way. That would be a feature in upstream Girder.

**Comment by matthewma7** [comment]
Yes. I personally think Girder should expose [these](https://github.com/girder/girder/blob/master/girder/utility/webroot.mako#L25-L30) in with an public endpoint. If we would like, I could at least create an issue for that.

**Comment by matthewma7** [comment]
Close by https://github.com/girder/girder_web_components/pull/69 with the quick fix version proposed above. Please go ahead and create new issues on related repo for handling this more explicitly.
