### ISSUE TITLE
Add Github Pages deployment to CI

### ISSUE THREAD

**Issue by subdavis** [girder/girder_web_components#68]
I think it would be nice if we could deploy the example app to GH pages so that other folks in D&A can poke around and give feedback/suggestions.  It's also generally good practice for communication.

This should be a pretty easy addition.  I'm happy to do it if this sounds valuable.

**Comment by jcfr** [comment]
Here is an example I worked on. Note that within CircleCI we can also distinguish between release deployment and regular build.
* See `deploy_website_command` in https://github.com/amueller/word_cloud/blob/b79b3d69a65643dbd421a027e66760a4398e91b3/.circleci/config.yml#L39-L44
* https://github.com/amueller/word_cloud/blob/master/doc/deploy-website.sh
