### ISSUE TITLE
Separate demo app from components library

### ISSUE THREAD

**Issue by brianhelba** [girder/girder_web_components#77]
At present, the demo app (bootstrapped by `src/main.js` and using components like `src/App.vue`) is located right next to the code for the components library (with its root at `src/index.js`).

Particularly considering that the demo app has hardcoded references to `data.kitware.com` and other deployment-specific details, it's good practice to strictly separate these two concerns. Although I (mostly) understand that the default rules for Vue-CLI will keep `src/main.js` out of the library if I import it downstream, having to rely on this undermines my confidence in this package as a deployment-agnostic library.

Can the demo app be moved to a separate directory, and can we ensure that the npm-published library does not include the demo app?

**Comment by subdavis** [comment]
When building in `--target lib` mode, you specify the entrypoint as `src/index.js`, and no code in the project references main.js

Seeing the line in package.json `vue-cli-service build --target lib --name girder src/index.js` gives me (personally) a high level of confidence in what the various build artifacts contain.

Is there any risk to shipping the library with dead code referencing DKC if something broke and this accidentally happenend?

I would agree that, for comprehension, having App.vue in that directory could be misleading.  Perhaps we could rename it "Demo.vue"?

**Comment by zachmullen** [comment]
+1 for excluding the demo code from the dist package. If that involves moving it into its own dir that's fine by me, that way the `src` dir would only contain library code.
